"""
================================================
  SIGN LANGUAGE DETECTION SYSTEM
  Phase 4 + 5: Real-Time Prediction + TTS
================================================

CONTROLS:
  Q        — Quit
  SPACE    — Pause / Resume
  C        — Clear text on screen
  T        — Toggle TTS on/off

FILES NEEDED (auto-generated by train_model.py):
  model.h5        — trained CNN model
  label_map.npy   — class label array

The system:
  1. Detects hand via MediaPipe
  2. Crops & preprocesses the hand region
  3. Predicts the sign with the CNN
  4. Displays sign + confidence on screen
  5. Speaks aloud via pyttsx3 (TTS)
  6. Builds a sentence as you sign letters
"""

import cv2
import numpy as np
import mediapipe as mp
import tensorflow as tf
import pyttsx3
import time
import threading
import sys
import os

# ── Config ────────────────────────────────────────────────
MODEL_PATH          = "model.h5"
LABEL_MAP_PATH      = "label_map.npy"
IMG_SIZE            = 64         # must match training
CONFIDENCE_THRESH   = 0.80       # only display if ≥ 80%
PADDING             = 30         # pixels around hand crop
STABLE_FRAMES       = 10         # frames sign must be stable before accepting
SPEAK_COOLDOWN      = 2.0        # seconds between TTS calls
# ──────────────────────────────────────────────────────────

# ── Load model & labels ───────────────────────────────────
if not os.path.exists(MODEL_PATH):
    print(f"❌ '{MODEL_PATH}' not found. Run train_model.py first.")
    sys.exit(1)
if not os.path.exists(LABEL_MAP_PATH):
    print(f"❌ '{LABEL_MAP_PATH}' not found. Run train_model.py first.")
    sys.exit(1)

print("🔄 Loading model …")
model     = tf.keras.models.load_model(MODEL_PATH)
classes   = np.load(LABEL_MAP_PATH, allow_pickle=True)
print(f"✅ Model loaded. Classes: {list(classes)}\n")

# ── TTS engine ────────────────────────────────────────────
tts_engine  = pyttsx3.init()
tts_engine.setProperty('rate', 160)
tts_engine.setProperty('volume', 0.9)

tts_enabled   = True
last_spoken   = ""
last_speak_t  = 0.0

def speak_async(text: str):
    """Speak in a background thread so it doesn't block the video loop."""
    def _run():
        tts_engine.say(text)
        tts_engine.runAndWait()
    t = threading.Thread(target=_run, daemon=True)
    t.start()

# ── MediaPipe ─────────────────────────────────────────────
mp_hands = mp.solutions.hands
mp_draw  = mp.solutions.drawing_utils
hands    = mp_hands.Hands(static_image_mode=False,
                          max_num_hands=1,
                          min_detection_confidence=0.75,
                          min_tracking_confidence=0.6)

# ── Webcam ────────────────────────────────────────────────
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("❌ Cannot open webcam.")
    sys.exit(1)

# ── State ─────────────────────────────────────────────────
sentence         = ""
prev_label       = None
stable_count     = 0
paused           = False
fps_list         = []
frame_time       = time.time()

# ── Color palette ─────────────────────────────────────────
C_BG    = (15,  15,  15)
C_GREEN = (80,  220, 100)
C_BLUE  = (255, 180, 50)
C_RED   = (60,  60,  220)
C_WHITE = (240, 240, 240)
C_GRAY  = (120, 120, 120)


def preprocess(crop: np.ndarray) -> np.ndarray:
    """Resize, normalise, add batch dim."""
    img = cv2.resize(crop, (IMG_SIZE, IMG_SIZE))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img.astype('float32') / 255.0
    return np.expand_dims(img, axis=0)


def draw_rounded_rect(img, x1, y1, x2, y2, r, color, thickness=-1):
    """Draw a rounded rectangle (filled or outline)."""
    cv2.rectangle(img, (x1+r, y1), (x2-r, y2), color, thickness)
    cv2.rectangle(img, (x1, y1+r), (x2, y2-r), color, thickness)
    for cx, cy in [(x1+r, y1+r), (x2-r, y1+r),
                   (x1+r, y2-r), (x2-r, y2-r)]:
        cv2.circle(img, (cx, cy), r, color, thickness)


print("🟢 Real-time detection started.")
print("   Controls:  Q=Quit  SPACE=Pause  C=Clear text  T=Toggle TTS\n")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame = cv2.flip(frame, 1)
    h, w  = frame.shape[:2]

    # ── FPS ───────────────────────────────────────────────
    now     = time.time()
    fps     = 1.0 / max(now - frame_time, 1e-6)
    frame_time = now
    fps_list.append(fps)
    if len(fps_list) > 30:
        fps_list.pop(0)
    avg_fps = sum(fps_list) / len(fps_list)

    predicted_label = None
    confidence      = 0.0
    hand_found      = False

    if not paused:
        rgb    = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        result = hands.process(rgb)

        if result.multi_hand_landmarks:
            hand_found = True
            for hand_lm in result.multi_hand_landmarks:
                mp_draw.draw_landmarks(
                    frame, hand_lm, mp_hands.HAND_CONNECTIONS,
                    mp_draw.DrawingSpec(color=(0,220,120), thickness=2, circle_radius=3),
                    mp_draw.DrawingSpec(color=(0,150,255), thickness=2)
                )

                xs = [lm.x * w for lm in hand_lm.landmark]
                ys = [lm.y * h for lm in hand_lm.landmark]
                x1 = max(0, int(min(xs)) - PADDING)
                y1 = max(0, int(min(ys)) - PADDING)
                x2 = min(w, int(max(xs)) + PADDING)
                y2 = min(h, int(max(ys)) + PADDING)

                if x2 > x1 and y2 > y1:
                    hand_crop = frame[y1:y2, x1:x2]
                    inp       = preprocess(hand_crop)
                    pred      = model.predict(inp, verbose=0)[0]
                    idx       = np.argmax(pred)
                    confidence = float(pred[idx])

                    if confidence >= CONFIDENCE_THRESH:
                        predicted_label = str(classes[idx])
                        box_color = C_GREEN
                    else:
                        predicted_label = "?"
                        box_color = C_GRAY

                    # Draw bounding box
                    cv2.rectangle(frame, (x1, y1), (x2, y2), box_color, 2)

        # ── Stability counter ─────────────────────────────
        if predicted_label and predicted_label != "?":
            if predicted_label == prev_label:
                stable_count += 1
            else:
                stable_count = 0
                prev_label   = predicted_label

            if stable_count == STABLE_FRAMES:
                # Add to sentence
                if predicted_label == "space":
                    sentence += " "
                elif predicted_label == "del":
                    sentence = sentence[:-1]
                else:
                    sentence += predicted_label

                # TTS
                if tts_enabled:
                    t_now = time.time()
                    if (predicted_label != last_spoken or
                            t_now - last_speak_t > SPEAK_COOLDOWN):
                        speak_async(predicted_label)
                        last_spoken  = predicted_label
                        last_speak_t = t_now
        else:
            stable_count = 0

    # ══ HUD Drawing ══════════════════════════════════════

    # Top bar
    cv2.rectangle(frame, (0, 0), (w, 55), (20, 20, 20), -1)

    # FPS
    cv2.putText(frame, f"FPS: {avg_fps:.1f}", (10, 38),
                cv2.FONT_HERSHEY_SIMPLEX, 0.8, C_BLUE, 2)

    # TTS indicator
    tts_str   = "TTS: ON" if tts_enabled else "TTS: OFF"
    tts_color = C_GREEN if tts_enabled else C_GRAY
    cv2.putText(frame, tts_str, (w - 120, 38),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, tts_color, 2)

    # PAUSED banner
    if paused:
        cv2.rectangle(frame, (0, 0), (w, h), (0, 0, 0), -1)   # darken
        cv2.putText(frame, "PAUSED", (w//2 - 100, h//2),
                    cv2.FONT_HERSHEY_DUPLEX, 2.0, C_BLUE, 3)

    # Prediction box (bottom-left)
    if predicted_label and not paused:
        conf_pct = int(confidence * 100)
        box_h    = 110
        cv2.rectangle(frame, (0, h - box_h), (280, h), (20, 20, 20), -1)

        label_disp = predicted_label if predicted_label != "?" else "Low conf."
        cv2.putText(frame, "Sign:", (10, h - box_h + 28),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.65, C_GRAY, 1)
        cv2.putText(frame, label_disp, (10, h - box_h + 72),
                    cv2.FONT_HERSHEY_DUPLEX, 1.8, C_GREEN, 3)

        # Confidence bar
        bar_x, bar_y, bar_w, bar_bh = 10, h - 20, 200, 10
        cv2.rectangle(frame, (bar_x, bar_y), (bar_x + bar_w, bar_y + bar_bh),
                      C_GRAY, -1)
        fill_w = int(bar_w * confidence)
        bar_color = C_GREEN if confidence >= CONFIDENCE_THRESH else C_RED
        cv2.rectangle(frame, (bar_x, bar_y), (bar_x + fill_w, bar_y + bar_bh),
                      bar_color, -1)
        cv2.putText(frame, f"{conf_pct}%", (bar_x + bar_w + 8, bar_y + 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, C_WHITE, 1)

    # Stability ring (small circle)
    if not paused and hand_found:
        ring_frac = stable_count / STABLE_FRAMES
        cv2.circle(frame, (w - 40, h - 40), 22, C_GRAY, 2)
        if ring_frac > 0:
            angle = int(360 * ring_frac)
            cv2.ellipse(frame, (w - 40, h - 40), (22, 22), -90, 0, angle, C_GREEN, 3)

    # Sentence panel (bottom strip)
    panel_y = h - 145
    cv2.rectangle(frame, (0, panel_y), (w, panel_y + 35), (30, 30, 30), -1)
    cv2.putText(frame, "Text: " + sentence[-50:],  # last 50 chars
                (10, panel_y + 24),
                cv2.FONT_HERSHEY_SIMPLEX, 0.72, C_WHITE, 2)

    # Controls hint (top-right)
    hints = ["Q:Quit", "SPC:Pause", "C:Clear", "T:TTS"]
    for i, hint in enumerate(hints):
        cv2.putText(frame, hint, (w - 115, 85 + i * 22),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, C_GRAY, 1)

    cv2.imshow("Sign Language Detector", frame)

    # ── Key handling ──────────────────────────────────────
    key = cv2.waitKey(1) & 0xFF

    if key == ord('q') or key == ord('Q'):
        break
    elif key == 32:                   # SPACE
        paused = not paused
        print("⏸  Paused" if paused else "▶  Resumed")
    elif key == ord('c') or key == ord('C'):
        sentence = ""
        print("🗑  Sentence cleared.")
    elif key == ord('t') or key == ord('T'):
        tts_enabled = not tts_enabled
        print(f"🔊 TTS {'enabled' if tts_enabled else 'disabled'}.")

cap.release()
cv2.destroyAllWindows()
hands.close()
print(f"\n👋 Session ended.")
print(f"📝 Final sentence: {sentence}")
